/*
 * This file is generated by gdbus-codegen, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from. Note that it links to GLib, so must comply with the
 * LGPL linking clauses.
 */

#pragma once

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for org.freedesktop.DBus.Peer */

#define TYPE_ORG_FREEDESKTOP_DBUS_PEER (org_freedesktop_dbus_peer_get_type ())
#define ORG_FREEDESKTOP_DBUS_PEER(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_FREEDESKTOP_DBUS_PEER, OrgFreedesktopDBusPeer))
#define IS_ORG_FREEDESKTOP_DBUS_PEER(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_FREEDESKTOP_DBUS_PEER))
#define ORG_FREEDESKTOP_DBUS_PEER_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), TYPE_ORG_FREEDESKTOP_DBUS_PEER, OrgFreedesktopDBusPeerIface))

struct _OrgFreedesktopDBusPeer;
typedef struct _OrgFreedesktopDBusPeer OrgFreedesktopDBusPeer;
typedef struct _OrgFreedesktopDBusPeerIface OrgFreedesktopDBusPeerIface;

struct _OrgFreedesktopDBusPeerIface
{
  GTypeInterface parent_iface;

  gboolean (*handle_get_machine_id) (
    OrgFreedesktopDBusPeer *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_ping) (
    OrgFreedesktopDBusPeer *object,
    GDBusMethodInvocation *invocation);

};

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrgFreedesktopDBusPeer, g_object_unref)
#endif

GType org_freedesktop_dbus_peer_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *org_freedesktop_dbus_peer_interface_info (void);
guint org_freedesktop_dbus_peer_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void org_freedesktop_dbus_peer_complete_ping (
    OrgFreedesktopDBusPeer *object,
    GDBusMethodInvocation *invocation);

void org_freedesktop_dbus_peer_complete_get_machine_id (
    OrgFreedesktopDBusPeer *object,
    GDBusMethodInvocation *invocation,
    const gchar *machine_uuid);



/* D-Bus method calls: */
void org_freedesktop_dbus_peer_call_ping (
    OrgFreedesktopDBusPeer *proxy,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_freedesktop_dbus_peer_call_ping_finish (
    OrgFreedesktopDBusPeer *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_freedesktop_dbus_peer_call_ping_sync (
    OrgFreedesktopDBusPeer *proxy,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GCancellable *cancellable,
    GError **error);

void org_freedesktop_dbus_peer_call_get_machine_id (
    OrgFreedesktopDBusPeer *proxy,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_freedesktop_dbus_peer_call_get_machine_id_finish (
    OrgFreedesktopDBusPeer *proxy,
    gchar **out_machine_uuid,
    GAsyncResult *res,
    GError **error);

gboolean org_freedesktop_dbus_peer_call_get_machine_id_sync (
    OrgFreedesktopDBusPeer *proxy,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    gchar **out_machine_uuid,
    GCancellable *cancellable,
    GError **error);



/* ---- */

#define TYPE_ORG_FREEDESKTOP_DBUS_PEER_PROXY (org_freedesktop_dbus_peer_proxy_get_type ())
#define ORG_FREEDESKTOP_DBUS_PEER_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_FREEDESKTOP_DBUS_PEER_PROXY, OrgFreedesktopDBusPeerProxy))
#define ORG_FREEDESKTOP_DBUS_PEER_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_ORG_FREEDESKTOP_DBUS_PEER_PROXY, OrgFreedesktopDBusPeerProxyClass))
#define ORG_FREEDESKTOP_DBUS_PEER_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_ORG_FREEDESKTOP_DBUS_PEER_PROXY, OrgFreedesktopDBusPeerProxyClass))
#define IS_ORG_FREEDESKTOP_DBUS_PEER_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_FREEDESKTOP_DBUS_PEER_PROXY))
#define IS_ORG_FREEDESKTOP_DBUS_PEER_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_ORG_FREEDESKTOP_DBUS_PEER_PROXY))

typedef struct _OrgFreedesktopDBusPeerProxy OrgFreedesktopDBusPeerProxy;
typedef struct _OrgFreedesktopDBusPeerProxyClass OrgFreedesktopDBusPeerProxyClass;
typedef struct _OrgFreedesktopDBusPeerProxyPrivate OrgFreedesktopDBusPeerProxyPrivate;

struct _OrgFreedesktopDBusPeerProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  OrgFreedesktopDBusPeerProxyPrivate *priv;
};

struct _OrgFreedesktopDBusPeerProxyClass
{
  GDBusProxyClass parent_class;
};

GType org_freedesktop_dbus_peer_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrgFreedesktopDBusPeerProxy, g_object_unref)
#endif

void org_freedesktop_dbus_peer_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
OrgFreedesktopDBusPeer *org_freedesktop_dbus_peer_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
OrgFreedesktopDBusPeer *org_freedesktop_dbus_peer_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void org_freedesktop_dbus_peer_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
OrgFreedesktopDBusPeer *org_freedesktop_dbus_peer_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
OrgFreedesktopDBusPeer *org_freedesktop_dbus_peer_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define TYPE_ORG_FREEDESKTOP_DBUS_PEER_SKELETON (org_freedesktop_dbus_peer_skeleton_get_type ())
#define ORG_FREEDESKTOP_DBUS_PEER_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_FREEDESKTOP_DBUS_PEER_SKELETON, OrgFreedesktopDBusPeerSkeleton))
#define ORG_FREEDESKTOP_DBUS_PEER_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_ORG_FREEDESKTOP_DBUS_PEER_SKELETON, OrgFreedesktopDBusPeerSkeletonClass))
#define ORG_FREEDESKTOP_DBUS_PEER_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_ORG_FREEDESKTOP_DBUS_PEER_SKELETON, OrgFreedesktopDBusPeerSkeletonClass))
#define IS_ORG_FREEDESKTOP_DBUS_PEER_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_FREEDESKTOP_DBUS_PEER_SKELETON))
#define IS_ORG_FREEDESKTOP_DBUS_PEER_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_ORG_FREEDESKTOP_DBUS_PEER_SKELETON))

typedef struct _OrgFreedesktopDBusPeerSkeleton OrgFreedesktopDBusPeerSkeleton;
typedef struct _OrgFreedesktopDBusPeerSkeletonClass OrgFreedesktopDBusPeerSkeletonClass;
typedef struct _OrgFreedesktopDBusPeerSkeletonPrivate OrgFreedesktopDBusPeerSkeletonPrivate;

struct _OrgFreedesktopDBusPeerSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  OrgFreedesktopDBusPeerSkeletonPrivate *priv;
};

struct _OrgFreedesktopDBusPeerSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType org_freedesktop_dbus_peer_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrgFreedesktopDBusPeerSkeleton, g_object_unref)
#endif

OrgFreedesktopDBusPeer *org_freedesktop_dbus_peer_skeleton_new (void);


/* ------------------------------------------------------------------------ */
/* Declarations for org.freedesktop.DBus.Introspectable */

#define TYPE_ORG_FREEDESKTOP_DBUS_INTROSPECTABLE (org_freedesktop_dbus_introspectable_get_type ())
#define ORG_FREEDESKTOP_DBUS_INTROSPECTABLE(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_FREEDESKTOP_DBUS_INTROSPECTABLE, OrgFreedesktopDBusIntrospectable))
#define IS_ORG_FREEDESKTOP_DBUS_INTROSPECTABLE(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_FREEDESKTOP_DBUS_INTROSPECTABLE))
#define ORG_FREEDESKTOP_DBUS_INTROSPECTABLE_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), TYPE_ORG_FREEDESKTOP_DBUS_INTROSPECTABLE, OrgFreedesktopDBusIntrospectableIface))

struct _OrgFreedesktopDBusIntrospectable;
typedef struct _OrgFreedesktopDBusIntrospectable OrgFreedesktopDBusIntrospectable;
typedef struct _OrgFreedesktopDBusIntrospectableIface OrgFreedesktopDBusIntrospectableIface;

struct _OrgFreedesktopDBusIntrospectableIface
{
  GTypeInterface parent_iface;

  gboolean (*handle_introspect) (
    OrgFreedesktopDBusIntrospectable *object,
    GDBusMethodInvocation *invocation);

};

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrgFreedesktopDBusIntrospectable, g_object_unref)
#endif

GType org_freedesktop_dbus_introspectable_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *org_freedesktop_dbus_introspectable_interface_info (void);
guint org_freedesktop_dbus_introspectable_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void org_freedesktop_dbus_introspectable_complete_introspect (
    OrgFreedesktopDBusIntrospectable *object,
    GDBusMethodInvocation *invocation,
    const gchar *xml_data);



/* D-Bus method calls: */
void org_freedesktop_dbus_introspectable_call_introspect (
    OrgFreedesktopDBusIntrospectable *proxy,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_freedesktop_dbus_introspectable_call_introspect_finish (
    OrgFreedesktopDBusIntrospectable *proxy,
    gchar **out_xml_data,
    GAsyncResult *res,
    GError **error);

gboolean org_freedesktop_dbus_introspectable_call_introspect_sync (
    OrgFreedesktopDBusIntrospectable *proxy,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    gchar **out_xml_data,
    GCancellable *cancellable,
    GError **error);



/* ---- */

#define TYPE_ORG_FREEDESKTOP_DBUS_INTROSPECTABLE_PROXY (org_freedesktop_dbus_introspectable_proxy_get_type ())
#define ORG_FREEDESKTOP_DBUS_INTROSPECTABLE_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_FREEDESKTOP_DBUS_INTROSPECTABLE_PROXY, OrgFreedesktopDBusIntrospectableProxy))
#define ORG_FREEDESKTOP_DBUS_INTROSPECTABLE_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_ORG_FREEDESKTOP_DBUS_INTROSPECTABLE_PROXY, OrgFreedesktopDBusIntrospectableProxyClass))
#define ORG_FREEDESKTOP_DBUS_INTROSPECTABLE_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_ORG_FREEDESKTOP_DBUS_INTROSPECTABLE_PROXY, OrgFreedesktopDBusIntrospectableProxyClass))
#define IS_ORG_FREEDESKTOP_DBUS_INTROSPECTABLE_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_FREEDESKTOP_DBUS_INTROSPECTABLE_PROXY))
#define IS_ORG_FREEDESKTOP_DBUS_INTROSPECTABLE_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_ORG_FREEDESKTOP_DBUS_INTROSPECTABLE_PROXY))

typedef struct _OrgFreedesktopDBusIntrospectableProxy OrgFreedesktopDBusIntrospectableProxy;
typedef struct _OrgFreedesktopDBusIntrospectableProxyClass OrgFreedesktopDBusIntrospectableProxyClass;
typedef struct _OrgFreedesktopDBusIntrospectableProxyPrivate OrgFreedesktopDBusIntrospectableProxyPrivate;

struct _OrgFreedesktopDBusIntrospectableProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  OrgFreedesktopDBusIntrospectableProxyPrivate *priv;
};

struct _OrgFreedesktopDBusIntrospectableProxyClass
{
  GDBusProxyClass parent_class;
};

GType org_freedesktop_dbus_introspectable_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrgFreedesktopDBusIntrospectableProxy, g_object_unref)
#endif

void org_freedesktop_dbus_introspectable_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
OrgFreedesktopDBusIntrospectable *org_freedesktop_dbus_introspectable_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
OrgFreedesktopDBusIntrospectable *org_freedesktop_dbus_introspectable_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void org_freedesktop_dbus_introspectable_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
OrgFreedesktopDBusIntrospectable *org_freedesktop_dbus_introspectable_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
OrgFreedesktopDBusIntrospectable *org_freedesktop_dbus_introspectable_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define TYPE_ORG_FREEDESKTOP_DBUS_INTROSPECTABLE_SKELETON (org_freedesktop_dbus_introspectable_skeleton_get_type ())
#define ORG_FREEDESKTOP_DBUS_INTROSPECTABLE_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_FREEDESKTOP_DBUS_INTROSPECTABLE_SKELETON, OrgFreedesktopDBusIntrospectableSkeleton))
#define ORG_FREEDESKTOP_DBUS_INTROSPECTABLE_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_ORG_FREEDESKTOP_DBUS_INTROSPECTABLE_SKELETON, OrgFreedesktopDBusIntrospectableSkeletonClass))
#define ORG_FREEDESKTOP_DBUS_INTROSPECTABLE_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_ORG_FREEDESKTOP_DBUS_INTROSPECTABLE_SKELETON, OrgFreedesktopDBusIntrospectableSkeletonClass))
#define IS_ORG_FREEDESKTOP_DBUS_INTROSPECTABLE_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_FREEDESKTOP_DBUS_INTROSPECTABLE_SKELETON))
#define IS_ORG_FREEDESKTOP_DBUS_INTROSPECTABLE_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_ORG_FREEDESKTOP_DBUS_INTROSPECTABLE_SKELETON))

typedef struct _OrgFreedesktopDBusIntrospectableSkeleton OrgFreedesktopDBusIntrospectableSkeleton;
typedef struct _OrgFreedesktopDBusIntrospectableSkeletonClass OrgFreedesktopDBusIntrospectableSkeletonClass;
typedef struct _OrgFreedesktopDBusIntrospectableSkeletonPrivate OrgFreedesktopDBusIntrospectableSkeletonPrivate;

struct _OrgFreedesktopDBusIntrospectableSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  OrgFreedesktopDBusIntrospectableSkeletonPrivate *priv;
};

struct _OrgFreedesktopDBusIntrospectableSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType org_freedesktop_dbus_introspectable_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrgFreedesktopDBusIntrospectableSkeleton, g_object_unref)
#endif

OrgFreedesktopDBusIntrospectable *org_freedesktop_dbus_introspectable_skeleton_new (void);


/* ------------------------------------------------------------------------ */
/* Declarations for org.freedesktop.DBus.Properties */

#define TYPE_ORG_FREEDESKTOP_DBUS_PROPERTIES (org_freedesktop_dbus_properties_get_type ())
#define ORG_FREEDESKTOP_DBUS_PROPERTIES(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_FREEDESKTOP_DBUS_PROPERTIES, OrgFreedesktopDBusProperties))
#define IS_ORG_FREEDESKTOP_DBUS_PROPERTIES(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_FREEDESKTOP_DBUS_PROPERTIES))
#define ORG_FREEDESKTOP_DBUS_PROPERTIES_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), TYPE_ORG_FREEDESKTOP_DBUS_PROPERTIES, OrgFreedesktopDBusPropertiesIface))

struct _OrgFreedesktopDBusProperties;
typedef struct _OrgFreedesktopDBusProperties OrgFreedesktopDBusProperties;
typedef struct _OrgFreedesktopDBusPropertiesIface OrgFreedesktopDBusPropertiesIface;

struct _OrgFreedesktopDBusPropertiesIface
{
  GTypeInterface parent_iface;


  gboolean (*handle_get) (
    OrgFreedesktopDBusProperties *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_interface_name,
    const gchar *arg_property_name);

  gboolean (*handle_get_all) (
    OrgFreedesktopDBusProperties *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_interface_name);

  gboolean (*handle_set) (
    OrgFreedesktopDBusProperties *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_interface_name,
    const gchar *arg_property_name,
    GVariant *arg_value);

  void (*properties_changed) (
    OrgFreedesktopDBusProperties *object,
    const gchar *arg_interface_name,
    GVariant *arg_changed_properties,
    const gchar *const *arg_invalidated_properties);

};

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrgFreedesktopDBusProperties, g_object_unref)
#endif

GType org_freedesktop_dbus_properties_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *org_freedesktop_dbus_properties_interface_info (void);
guint org_freedesktop_dbus_properties_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void org_freedesktop_dbus_properties_complete_get (
    OrgFreedesktopDBusProperties *object,
    GDBusMethodInvocation *invocation,
    GVariant *value);

void org_freedesktop_dbus_properties_complete_get_all (
    OrgFreedesktopDBusProperties *object,
    GDBusMethodInvocation *invocation,
    GVariant *props);

void org_freedesktop_dbus_properties_complete_set (
    OrgFreedesktopDBusProperties *object,
    GDBusMethodInvocation *invocation);



/* D-Bus signal emissions functions: */
void org_freedesktop_dbus_properties_emit_properties_changed (
    OrgFreedesktopDBusProperties *object,
    const gchar *arg_interface_name,
    GVariant *arg_changed_properties,
    const gchar *const *arg_invalidated_properties);



/* D-Bus method calls: */
void org_freedesktop_dbus_properties_call_get (
    OrgFreedesktopDBusProperties *proxy,
    const gchar *arg_interface_name,
    const gchar *arg_property_name,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_freedesktop_dbus_properties_call_get_finish (
    OrgFreedesktopDBusProperties *proxy,
    GVariant **out_value,
    GAsyncResult *res,
    GError **error);

gboolean org_freedesktop_dbus_properties_call_get_sync (
    OrgFreedesktopDBusProperties *proxy,
    const gchar *arg_interface_name,
    const gchar *arg_property_name,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GVariant **out_value,
    GCancellable *cancellable,
    GError **error);

void org_freedesktop_dbus_properties_call_get_all (
    OrgFreedesktopDBusProperties *proxy,
    const gchar *arg_interface_name,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_freedesktop_dbus_properties_call_get_all_finish (
    OrgFreedesktopDBusProperties *proxy,
    GVariant **out_props,
    GAsyncResult *res,
    GError **error);

gboolean org_freedesktop_dbus_properties_call_get_all_sync (
    OrgFreedesktopDBusProperties *proxy,
    const gchar *arg_interface_name,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GVariant **out_props,
    GCancellable *cancellable,
    GError **error);

void org_freedesktop_dbus_properties_call_set (
    OrgFreedesktopDBusProperties *proxy,
    const gchar *arg_interface_name,
    const gchar *arg_property_name,
    GVariant *arg_value,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_freedesktop_dbus_properties_call_set_finish (
    OrgFreedesktopDBusProperties *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_freedesktop_dbus_properties_call_set_sync (
    OrgFreedesktopDBusProperties *proxy,
    const gchar *arg_interface_name,
    const gchar *arg_property_name,
    GVariant *arg_value,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GCancellable *cancellable,
    GError **error);



/* ---- */

#define TYPE_ORG_FREEDESKTOP_DBUS_PROPERTIES_PROXY (org_freedesktop_dbus_properties_proxy_get_type ())
#define ORG_FREEDESKTOP_DBUS_PROPERTIES_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_FREEDESKTOP_DBUS_PROPERTIES_PROXY, OrgFreedesktopDBusPropertiesProxy))
#define ORG_FREEDESKTOP_DBUS_PROPERTIES_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_ORG_FREEDESKTOP_DBUS_PROPERTIES_PROXY, OrgFreedesktopDBusPropertiesProxyClass))
#define ORG_FREEDESKTOP_DBUS_PROPERTIES_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_ORG_FREEDESKTOP_DBUS_PROPERTIES_PROXY, OrgFreedesktopDBusPropertiesProxyClass))
#define IS_ORG_FREEDESKTOP_DBUS_PROPERTIES_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_FREEDESKTOP_DBUS_PROPERTIES_PROXY))
#define IS_ORG_FREEDESKTOP_DBUS_PROPERTIES_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_ORG_FREEDESKTOP_DBUS_PROPERTIES_PROXY))

typedef struct _OrgFreedesktopDBusPropertiesProxy OrgFreedesktopDBusPropertiesProxy;
typedef struct _OrgFreedesktopDBusPropertiesProxyClass OrgFreedesktopDBusPropertiesProxyClass;
typedef struct _OrgFreedesktopDBusPropertiesProxyPrivate OrgFreedesktopDBusPropertiesProxyPrivate;

struct _OrgFreedesktopDBusPropertiesProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  OrgFreedesktopDBusPropertiesProxyPrivate *priv;
};

struct _OrgFreedesktopDBusPropertiesProxyClass
{
  GDBusProxyClass parent_class;
};

GType org_freedesktop_dbus_properties_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrgFreedesktopDBusPropertiesProxy, g_object_unref)
#endif

void org_freedesktop_dbus_properties_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
OrgFreedesktopDBusProperties *org_freedesktop_dbus_properties_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
OrgFreedesktopDBusProperties *org_freedesktop_dbus_properties_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void org_freedesktop_dbus_properties_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
OrgFreedesktopDBusProperties *org_freedesktop_dbus_properties_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
OrgFreedesktopDBusProperties *org_freedesktop_dbus_properties_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define TYPE_ORG_FREEDESKTOP_DBUS_PROPERTIES_SKELETON (org_freedesktop_dbus_properties_skeleton_get_type ())
#define ORG_FREEDESKTOP_DBUS_PROPERTIES_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_FREEDESKTOP_DBUS_PROPERTIES_SKELETON, OrgFreedesktopDBusPropertiesSkeleton))
#define ORG_FREEDESKTOP_DBUS_PROPERTIES_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_ORG_FREEDESKTOP_DBUS_PROPERTIES_SKELETON, OrgFreedesktopDBusPropertiesSkeletonClass))
#define ORG_FREEDESKTOP_DBUS_PROPERTIES_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_ORG_FREEDESKTOP_DBUS_PROPERTIES_SKELETON, OrgFreedesktopDBusPropertiesSkeletonClass))
#define IS_ORG_FREEDESKTOP_DBUS_PROPERTIES_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_FREEDESKTOP_DBUS_PROPERTIES_SKELETON))
#define IS_ORG_FREEDESKTOP_DBUS_PROPERTIES_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_ORG_FREEDESKTOP_DBUS_PROPERTIES_SKELETON))

typedef struct _OrgFreedesktopDBusPropertiesSkeleton OrgFreedesktopDBusPropertiesSkeleton;
typedef struct _OrgFreedesktopDBusPropertiesSkeletonClass OrgFreedesktopDBusPropertiesSkeletonClass;
typedef struct _OrgFreedesktopDBusPropertiesSkeletonPrivate OrgFreedesktopDBusPropertiesSkeletonPrivate;

struct _OrgFreedesktopDBusPropertiesSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  OrgFreedesktopDBusPropertiesSkeletonPrivate *priv;
};

struct _OrgFreedesktopDBusPropertiesSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType org_freedesktop_dbus_properties_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrgFreedesktopDBusPropertiesSkeleton, g_object_unref)
#endif

OrgFreedesktopDBusProperties *org_freedesktop_dbus_properties_skeleton_new (void);


/* ------------------------------------------------------------------------ */
/* Declarations for org.freedesktop.login1.Session */

#define TYPE_ORG_FREEDESKTOP_LOGIN1_SESSION (org_freedesktop_login1_session_get_type ())
#define ORG_FREEDESKTOP_LOGIN1_SESSION(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_FREEDESKTOP_LOGIN1_SESSION, OrgFreedesktopLogin1Session))
#define IS_ORG_FREEDESKTOP_LOGIN1_SESSION(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_FREEDESKTOP_LOGIN1_SESSION))
#define ORG_FREEDESKTOP_LOGIN1_SESSION_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), TYPE_ORG_FREEDESKTOP_LOGIN1_SESSION, OrgFreedesktopLogin1SessionIface))

struct _OrgFreedesktopLogin1Session;
typedef struct _OrgFreedesktopLogin1Session OrgFreedesktopLogin1Session;
typedef struct _OrgFreedesktopLogin1SessionIface OrgFreedesktopLogin1SessionIface;

struct _OrgFreedesktopLogin1SessionIface
{
  GTypeInterface parent_iface;



  gboolean (*handle_activate) (
    OrgFreedesktopLogin1Session *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_kill) (
    OrgFreedesktopLogin1Session *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_whom,
    gint arg_signal_number);

  gboolean (*handle_lock) (
    OrgFreedesktopLogin1Session *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_pause_device_complete) (
    OrgFreedesktopLogin1Session *object,
    GDBusMethodInvocation *invocation,
    guint arg_major,
    guint arg_minor);

  gboolean (*handle_release_control) (
    OrgFreedesktopLogin1Session *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_release_device) (
    OrgFreedesktopLogin1Session *object,
    GDBusMethodInvocation *invocation,
    guint arg_major,
    guint arg_minor);

  gboolean (*handle_set_brightness) (
    OrgFreedesktopLogin1Session *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_subsystem,
    const gchar *arg_name,
    guint arg_brightness);

  gboolean (*handle_set_class) (
    OrgFreedesktopLogin1Session *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_class);

  gboolean (*handle_set_display) (
    OrgFreedesktopLogin1Session *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_display);

  gboolean (*handle_set_idle_hint) (
    OrgFreedesktopLogin1Session *object,
    GDBusMethodInvocation *invocation,
    gboolean arg_idle);

  gboolean (*handle_set_locked_hint) (
    OrgFreedesktopLogin1Session *object,
    GDBusMethodInvocation *invocation,
    gboolean arg_locked);

  gboolean (*handle_set_tty) (
    OrgFreedesktopLogin1Session *object,
    GDBusMethodInvocation *invocation,
    GUnixFDList *fd_list,
    GVariant *arg_tty_fd);

  gboolean (*handle_set_type) (
    OrgFreedesktopLogin1Session *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_type);

  gboolean (*handle_take_control) (
    OrgFreedesktopLogin1Session *object,
    GDBusMethodInvocation *invocation,
    gboolean arg_force);

  gboolean (*handle_take_device) (
    OrgFreedesktopLogin1Session *object,
    GDBusMethodInvocation *invocation,
    GUnixFDList *fd_list,
    guint arg_major,
    guint arg_minor);

  gboolean (*handle_terminate) (
    OrgFreedesktopLogin1Session *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_unlock) (
    OrgFreedesktopLogin1Session *object,
    GDBusMethodInvocation *invocation);

  gboolean  (*get_active) (OrgFreedesktopLogin1Session *object);

  guint  (*get_audit) (OrgFreedesktopLogin1Session *object);

  gboolean  (*get_can_idle) (OrgFreedesktopLogin1Session *object);

  gboolean  (*get_can_lock) (OrgFreedesktopLogin1Session *object);

  const gchar * (*get_class) (OrgFreedesktopLogin1Session *object);

  const gchar * (*get_desktop) (OrgFreedesktopLogin1Session *object);

  const gchar * (*get_display) (OrgFreedesktopLogin1Session *object);

  const gchar * (*get_id) (OrgFreedesktopLogin1Session *object);

  gboolean  (*get_idle_hint) (OrgFreedesktopLogin1Session *object);

  guint64  (*get_idle_since_hint) (OrgFreedesktopLogin1Session *object);

  guint64  (*get_idle_since_hint_monotonic) (OrgFreedesktopLogin1Session *object);

  guint  (*get_leader) (OrgFreedesktopLogin1Session *object);

  gboolean  (*get_locked_hint) (OrgFreedesktopLogin1Session *object);

  const gchar * (*get_name) (OrgFreedesktopLogin1Session *object);

  gboolean  (*get_remote) (OrgFreedesktopLogin1Session *object);

  const gchar * (*get_remote_host) (OrgFreedesktopLogin1Session *object);

  const gchar * (*get_remote_user) (OrgFreedesktopLogin1Session *object);

  const gchar * (*get_scope) (OrgFreedesktopLogin1Session *object);

  GVariant * (*get_seat) (OrgFreedesktopLogin1Session *object);

  const gchar * (*get_service) (OrgFreedesktopLogin1Session *object);

  const gchar * (*get_state) (OrgFreedesktopLogin1Session *object);

  guint64  (*get_timestamp) (OrgFreedesktopLogin1Session *object);

  guint64  (*get_timestamp_monotonic) (OrgFreedesktopLogin1Session *object);

  const gchar * (*get_tty) (OrgFreedesktopLogin1Session *object);

  const gchar * (*get_type_) (OrgFreedesktopLogin1Session *object);

  GVariant * (*get_user) (OrgFreedesktopLogin1Session *object);

  guint  (*get_vtnr) (OrgFreedesktopLogin1Session *object);

  void (*lock) (
    OrgFreedesktopLogin1Session *object);

  void (*pause_device) (
    OrgFreedesktopLogin1Session *object,
    guint arg_major,
    guint arg_minor,
    const gchar *arg_type);

  void (*resume_device) (
    OrgFreedesktopLogin1Session *object,
    guint arg_major,
    guint arg_minor,
    GVariant *arg_fd);

  void (*unlock) (
    OrgFreedesktopLogin1Session *object);

};

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrgFreedesktopLogin1Session, g_object_unref)
#endif

GType org_freedesktop_login1_session_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *org_freedesktop_login1_session_interface_info (void);
guint org_freedesktop_login1_session_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void org_freedesktop_login1_session_complete_terminate (
    OrgFreedesktopLogin1Session *object,
    GDBusMethodInvocation *invocation);

void org_freedesktop_login1_session_complete_activate (
    OrgFreedesktopLogin1Session *object,
    GDBusMethodInvocation *invocation);

void org_freedesktop_login1_session_complete_lock (
    OrgFreedesktopLogin1Session *object,
    GDBusMethodInvocation *invocation);

void org_freedesktop_login1_session_complete_unlock (
    OrgFreedesktopLogin1Session *object,
    GDBusMethodInvocation *invocation);

void org_freedesktop_login1_session_complete_set_idle_hint (
    OrgFreedesktopLogin1Session *object,
    GDBusMethodInvocation *invocation);

void org_freedesktop_login1_session_complete_set_locked_hint (
    OrgFreedesktopLogin1Session *object,
    GDBusMethodInvocation *invocation);

void org_freedesktop_login1_session_complete_kill (
    OrgFreedesktopLogin1Session *object,
    GDBusMethodInvocation *invocation);

void org_freedesktop_login1_session_complete_take_control (
    OrgFreedesktopLogin1Session *object,
    GDBusMethodInvocation *invocation);

void org_freedesktop_login1_session_complete_release_control (
    OrgFreedesktopLogin1Session *object,
    GDBusMethodInvocation *invocation);

void org_freedesktop_login1_session_complete_set_type (
    OrgFreedesktopLogin1Session *object,
    GDBusMethodInvocation *invocation);

void org_freedesktop_login1_session_complete_set_class (
    OrgFreedesktopLogin1Session *object,
    GDBusMethodInvocation *invocation);

void org_freedesktop_login1_session_complete_set_display (
    OrgFreedesktopLogin1Session *object,
    GDBusMethodInvocation *invocation);

void org_freedesktop_login1_session_complete_set_tty (
    OrgFreedesktopLogin1Session *object,
    GDBusMethodInvocation *invocation,
    GUnixFDList *fd_list);

void org_freedesktop_login1_session_complete_take_device (
    OrgFreedesktopLogin1Session *object,
    GDBusMethodInvocation *invocation,
    GUnixFDList *fd_list,
    GVariant *fd,
    gboolean inactive);

void org_freedesktop_login1_session_complete_release_device (
    OrgFreedesktopLogin1Session *object,
    GDBusMethodInvocation *invocation);

void org_freedesktop_login1_session_complete_pause_device_complete (
    OrgFreedesktopLogin1Session *object,
    GDBusMethodInvocation *invocation);

void org_freedesktop_login1_session_complete_set_brightness (
    OrgFreedesktopLogin1Session *object,
    GDBusMethodInvocation *invocation);



/* D-Bus signal emissions functions: */
void org_freedesktop_login1_session_emit_pause_device (
    OrgFreedesktopLogin1Session *object,
    guint arg_major,
    guint arg_minor,
    const gchar *arg_type);

void org_freedesktop_login1_session_emit_resume_device (
    OrgFreedesktopLogin1Session *object,
    guint arg_major,
    guint arg_minor,
    GVariant *arg_fd);

void org_freedesktop_login1_session_emit_lock (
    OrgFreedesktopLogin1Session *object);

void org_freedesktop_login1_session_emit_unlock (
    OrgFreedesktopLogin1Session *object);



/* D-Bus method calls: */
void org_freedesktop_login1_session_call_terminate (
    OrgFreedesktopLogin1Session *proxy,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_freedesktop_login1_session_call_terminate_finish (
    OrgFreedesktopLogin1Session *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_freedesktop_login1_session_call_terminate_sync (
    OrgFreedesktopLogin1Session *proxy,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GCancellable *cancellable,
    GError **error);

void org_freedesktop_login1_session_call_activate (
    OrgFreedesktopLogin1Session *proxy,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_freedesktop_login1_session_call_activate_finish (
    OrgFreedesktopLogin1Session *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_freedesktop_login1_session_call_activate_sync (
    OrgFreedesktopLogin1Session *proxy,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GCancellable *cancellable,
    GError **error);

void org_freedesktop_login1_session_call_lock (
    OrgFreedesktopLogin1Session *proxy,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_freedesktop_login1_session_call_lock_finish (
    OrgFreedesktopLogin1Session *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_freedesktop_login1_session_call_lock_sync (
    OrgFreedesktopLogin1Session *proxy,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GCancellable *cancellable,
    GError **error);

void org_freedesktop_login1_session_call_unlock (
    OrgFreedesktopLogin1Session *proxy,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_freedesktop_login1_session_call_unlock_finish (
    OrgFreedesktopLogin1Session *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_freedesktop_login1_session_call_unlock_sync (
    OrgFreedesktopLogin1Session *proxy,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GCancellable *cancellable,
    GError **error);

void org_freedesktop_login1_session_call_set_idle_hint (
    OrgFreedesktopLogin1Session *proxy,
    gboolean arg_idle,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_freedesktop_login1_session_call_set_idle_hint_finish (
    OrgFreedesktopLogin1Session *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_freedesktop_login1_session_call_set_idle_hint_sync (
    OrgFreedesktopLogin1Session *proxy,
    gboolean arg_idle,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GCancellable *cancellable,
    GError **error);

void org_freedesktop_login1_session_call_set_locked_hint (
    OrgFreedesktopLogin1Session *proxy,
    gboolean arg_locked,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_freedesktop_login1_session_call_set_locked_hint_finish (
    OrgFreedesktopLogin1Session *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_freedesktop_login1_session_call_set_locked_hint_sync (
    OrgFreedesktopLogin1Session *proxy,
    gboolean arg_locked,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GCancellable *cancellable,
    GError **error);

void org_freedesktop_login1_session_call_kill (
    OrgFreedesktopLogin1Session *proxy,
    const gchar *arg_whom,
    gint arg_signal_number,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_freedesktop_login1_session_call_kill_finish (
    OrgFreedesktopLogin1Session *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_freedesktop_login1_session_call_kill_sync (
    OrgFreedesktopLogin1Session *proxy,
    const gchar *arg_whom,
    gint arg_signal_number,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GCancellable *cancellable,
    GError **error);

void org_freedesktop_login1_session_call_take_control (
    OrgFreedesktopLogin1Session *proxy,
    gboolean arg_force,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_freedesktop_login1_session_call_take_control_finish (
    OrgFreedesktopLogin1Session *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_freedesktop_login1_session_call_take_control_sync (
    OrgFreedesktopLogin1Session *proxy,
    gboolean arg_force,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GCancellable *cancellable,
    GError **error);

void org_freedesktop_login1_session_call_release_control (
    OrgFreedesktopLogin1Session *proxy,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_freedesktop_login1_session_call_release_control_finish (
    OrgFreedesktopLogin1Session *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_freedesktop_login1_session_call_release_control_sync (
    OrgFreedesktopLogin1Session *proxy,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GCancellable *cancellable,
    GError **error);

void org_freedesktop_login1_session_call_set_type (
    OrgFreedesktopLogin1Session *proxy,
    const gchar *arg_type,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_freedesktop_login1_session_call_set_type_finish (
    OrgFreedesktopLogin1Session *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_freedesktop_login1_session_call_set_type_sync (
    OrgFreedesktopLogin1Session *proxy,
    const gchar *arg_type,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GCancellable *cancellable,
    GError **error);

void org_freedesktop_login1_session_call_set_class (
    OrgFreedesktopLogin1Session *proxy,
    const gchar *arg_class,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_freedesktop_login1_session_call_set_class_finish (
    OrgFreedesktopLogin1Session *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_freedesktop_login1_session_call_set_class_sync (
    OrgFreedesktopLogin1Session *proxy,
    const gchar *arg_class,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GCancellable *cancellable,
    GError **error);

void org_freedesktop_login1_session_call_set_display (
    OrgFreedesktopLogin1Session *proxy,
    const gchar *arg_display,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_freedesktop_login1_session_call_set_display_finish (
    OrgFreedesktopLogin1Session *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_freedesktop_login1_session_call_set_display_sync (
    OrgFreedesktopLogin1Session *proxy,
    const gchar *arg_display,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GCancellable *cancellable,
    GError **error);

void org_freedesktop_login1_session_call_set_tty (
    OrgFreedesktopLogin1Session *proxy,
    GVariant *arg_tty_fd,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GUnixFDList *fd_list,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_freedesktop_login1_session_call_set_tty_finish (
    OrgFreedesktopLogin1Session *proxy,
    GUnixFDList **out_fd_list,
    GAsyncResult *res,
    GError **error);

gboolean org_freedesktop_login1_session_call_set_tty_sync (
    OrgFreedesktopLogin1Session *proxy,
    GVariant *arg_tty_fd,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GUnixFDList  *fd_list,
    GUnixFDList **out_fd_list,
    GCancellable *cancellable,
    GError **error);

void org_freedesktop_login1_session_call_take_device (
    OrgFreedesktopLogin1Session *proxy,
    guint arg_major,
    guint arg_minor,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GUnixFDList *fd_list,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_freedesktop_login1_session_call_take_device_finish (
    OrgFreedesktopLogin1Session *proxy,
    GVariant **out_fd,
    gboolean *out_inactive,
    GUnixFDList **out_fd_list,
    GAsyncResult *res,
    GError **error);

gboolean org_freedesktop_login1_session_call_take_device_sync (
    OrgFreedesktopLogin1Session *proxy,
    guint arg_major,
    guint arg_minor,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GUnixFDList  *fd_list,
    GVariant **out_fd,
    gboolean *out_inactive,
    GUnixFDList **out_fd_list,
    GCancellable *cancellable,
    GError **error);

void org_freedesktop_login1_session_call_release_device (
    OrgFreedesktopLogin1Session *proxy,
    guint arg_major,
    guint arg_minor,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_freedesktop_login1_session_call_release_device_finish (
    OrgFreedesktopLogin1Session *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_freedesktop_login1_session_call_release_device_sync (
    OrgFreedesktopLogin1Session *proxy,
    guint arg_major,
    guint arg_minor,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GCancellable *cancellable,
    GError **error);

void org_freedesktop_login1_session_call_pause_device_complete (
    OrgFreedesktopLogin1Session *proxy,
    guint arg_major,
    guint arg_minor,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_freedesktop_login1_session_call_pause_device_complete_finish (
    OrgFreedesktopLogin1Session *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_freedesktop_login1_session_call_pause_device_complete_sync (
    OrgFreedesktopLogin1Session *proxy,
    guint arg_major,
    guint arg_minor,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GCancellable *cancellable,
    GError **error);

void org_freedesktop_login1_session_call_set_brightness (
    OrgFreedesktopLogin1Session *proxy,
    const gchar *arg_subsystem,
    const gchar *arg_name,
    guint arg_brightness,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_freedesktop_login1_session_call_set_brightness_finish (
    OrgFreedesktopLogin1Session *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_freedesktop_login1_session_call_set_brightness_sync (
    OrgFreedesktopLogin1Session *proxy,
    const gchar *arg_subsystem,
    const gchar *arg_name,
    guint arg_brightness,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GCancellable *cancellable,
    GError **error);



/* D-Bus property accessors: */
const gchar *org_freedesktop_login1_session_get_id (OrgFreedesktopLogin1Session *object);
gchar *org_freedesktop_login1_session_dup_id (OrgFreedesktopLogin1Session *object);
void org_freedesktop_login1_session_set_id (OrgFreedesktopLogin1Session *object, const gchar *value);

GVariant *org_freedesktop_login1_session_get_user (OrgFreedesktopLogin1Session *object);
GVariant *org_freedesktop_login1_session_dup_user (OrgFreedesktopLogin1Session *object);
void org_freedesktop_login1_session_set_user (OrgFreedesktopLogin1Session *object, GVariant *value);

const gchar *org_freedesktop_login1_session_get_name (OrgFreedesktopLogin1Session *object);
gchar *org_freedesktop_login1_session_dup_name (OrgFreedesktopLogin1Session *object);
void org_freedesktop_login1_session_set_name (OrgFreedesktopLogin1Session *object, const gchar *value);

guint64 org_freedesktop_login1_session_get_timestamp (OrgFreedesktopLogin1Session *object);
void org_freedesktop_login1_session_set_timestamp (OrgFreedesktopLogin1Session *object, guint64 value);

guint64 org_freedesktop_login1_session_get_timestamp_monotonic (OrgFreedesktopLogin1Session *object);
void org_freedesktop_login1_session_set_timestamp_monotonic (OrgFreedesktopLogin1Session *object, guint64 value);

guint org_freedesktop_login1_session_get_vtnr (OrgFreedesktopLogin1Session *object);
void org_freedesktop_login1_session_set_vtnr (OrgFreedesktopLogin1Session *object, guint value);

GVariant *org_freedesktop_login1_session_get_seat (OrgFreedesktopLogin1Session *object);
GVariant *org_freedesktop_login1_session_dup_seat (OrgFreedesktopLogin1Session *object);
void org_freedesktop_login1_session_set_seat (OrgFreedesktopLogin1Session *object, GVariant *value);

const gchar *org_freedesktop_login1_session_get_tty (OrgFreedesktopLogin1Session *object);
gchar *org_freedesktop_login1_session_dup_tty (OrgFreedesktopLogin1Session *object);
void org_freedesktop_login1_session_set_tty (OrgFreedesktopLogin1Session *object, const gchar *value);

const gchar *org_freedesktop_login1_session_get_display (OrgFreedesktopLogin1Session *object);
gchar *org_freedesktop_login1_session_dup_display (OrgFreedesktopLogin1Session *object);
void org_freedesktop_login1_session_set_display (OrgFreedesktopLogin1Session *object, const gchar *value);

gboolean org_freedesktop_login1_session_get_remote (OrgFreedesktopLogin1Session *object);
void org_freedesktop_login1_session_set_remote (OrgFreedesktopLogin1Session *object, gboolean value);

const gchar *org_freedesktop_login1_session_get_remote_host (OrgFreedesktopLogin1Session *object);
gchar *org_freedesktop_login1_session_dup_remote_host (OrgFreedesktopLogin1Session *object);
void org_freedesktop_login1_session_set_remote_host (OrgFreedesktopLogin1Session *object, const gchar *value);

const gchar *org_freedesktop_login1_session_get_remote_user (OrgFreedesktopLogin1Session *object);
gchar *org_freedesktop_login1_session_dup_remote_user (OrgFreedesktopLogin1Session *object);
void org_freedesktop_login1_session_set_remote_user (OrgFreedesktopLogin1Session *object, const gchar *value);

const gchar *org_freedesktop_login1_session_get_service (OrgFreedesktopLogin1Session *object);
gchar *org_freedesktop_login1_session_dup_service (OrgFreedesktopLogin1Session *object);
void org_freedesktop_login1_session_set_service (OrgFreedesktopLogin1Session *object, const gchar *value);

const gchar *org_freedesktop_login1_session_get_desktop (OrgFreedesktopLogin1Session *object);
gchar *org_freedesktop_login1_session_dup_desktop (OrgFreedesktopLogin1Session *object);
void org_freedesktop_login1_session_set_desktop (OrgFreedesktopLogin1Session *object, const gchar *value);

const gchar *org_freedesktop_login1_session_get_scope (OrgFreedesktopLogin1Session *object);
gchar *org_freedesktop_login1_session_dup_scope (OrgFreedesktopLogin1Session *object);
void org_freedesktop_login1_session_set_scope (OrgFreedesktopLogin1Session *object, const gchar *value);

guint org_freedesktop_login1_session_get_leader (OrgFreedesktopLogin1Session *object);
void org_freedesktop_login1_session_set_leader (OrgFreedesktopLogin1Session *object, guint value);

guint org_freedesktop_login1_session_get_audit (OrgFreedesktopLogin1Session *object);
void org_freedesktop_login1_session_set_audit (OrgFreedesktopLogin1Session *object, guint value);

const gchar *org_freedesktop_login1_session_get_type_ (OrgFreedesktopLogin1Session *object);
gchar *org_freedesktop_login1_session_dup_type_ (OrgFreedesktopLogin1Session *object);
void org_freedesktop_login1_session_set_type_ (OrgFreedesktopLogin1Session *object, const gchar *value);

const gchar *org_freedesktop_login1_session_get_class (OrgFreedesktopLogin1Session *object);
gchar *org_freedesktop_login1_session_dup_class (OrgFreedesktopLogin1Session *object);
void org_freedesktop_login1_session_set_class (OrgFreedesktopLogin1Session *object, const gchar *value);

gboolean org_freedesktop_login1_session_get_active (OrgFreedesktopLogin1Session *object);
void org_freedesktop_login1_session_set_active (OrgFreedesktopLogin1Session *object, gboolean value);

const gchar *org_freedesktop_login1_session_get_state (OrgFreedesktopLogin1Session *object);
gchar *org_freedesktop_login1_session_dup_state (OrgFreedesktopLogin1Session *object);
void org_freedesktop_login1_session_set_state (OrgFreedesktopLogin1Session *object, const gchar *value);

gboolean org_freedesktop_login1_session_get_idle_hint (OrgFreedesktopLogin1Session *object);
void org_freedesktop_login1_session_set_idle_hint (OrgFreedesktopLogin1Session *object, gboolean value);

guint64 org_freedesktop_login1_session_get_idle_since_hint (OrgFreedesktopLogin1Session *object);
void org_freedesktop_login1_session_set_idle_since_hint (OrgFreedesktopLogin1Session *object, guint64 value);

guint64 org_freedesktop_login1_session_get_idle_since_hint_monotonic (OrgFreedesktopLogin1Session *object);
void org_freedesktop_login1_session_set_idle_since_hint_monotonic (OrgFreedesktopLogin1Session *object, guint64 value);

gboolean org_freedesktop_login1_session_get_can_idle (OrgFreedesktopLogin1Session *object);
void org_freedesktop_login1_session_set_can_idle (OrgFreedesktopLogin1Session *object, gboolean value);

gboolean org_freedesktop_login1_session_get_can_lock (OrgFreedesktopLogin1Session *object);
void org_freedesktop_login1_session_set_can_lock (OrgFreedesktopLogin1Session *object, gboolean value);

gboolean org_freedesktop_login1_session_get_locked_hint (OrgFreedesktopLogin1Session *object);
void org_freedesktop_login1_session_set_locked_hint (OrgFreedesktopLogin1Session *object, gboolean value);


/* ---- */

#define TYPE_ORG_FREEDESKTOP_LOGIN1_SESSION_PROXY (org_freedesktop_login1_session_proxy_get_type ())
#define ORG_FREEDESKTOP_LOGIN1_SESSION_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_FREEDESKTOP_LOGIN1_SESSION_PROXY, OrgFreedesktopLogin1SessionProxy))
#define ORG_FREEDESKTOP_LOGIN1_SESSION_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_ORG_FREEDESKTOP_LOGIN1_SESSION_PROXY, OrgFreedesktopLogin1SessionProxyClass))
#define ORG_FREEDESKTOP_LOGIN1_SESSION_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_ORG_FREEDESKTOP_LOGIN1_SESSION_PROXY, OrgFreedesktopLogin1SessionProxyClass))
#define IS_ORG_FREEDESKTOP_LOGIN1_SESSION_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_FREEDESKTOP_LOGIN1_SESSION_PROXY))
#define IS_ORG_FREEDESKTOP_LOGIN1_SESSION_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_ORG_FREEDESKTOP_LOGIN1_SESSION_PROXY))

typedef struct _OrgFreedesktopLogin1SessionProxy OrgFreedesktopLogin1SessionProxy;
typedef struct _OrgFreedesktopLogin1SessionProxyClass OrgFreedesktopLogin1SessionProxyClass;
typedef struct _OrgFreedesktopLogin1SessionProxyPrivate OrgFreedesktopLogin1SessionProxyPrivate;

struct _OrgFreedesktopLogin1SessionProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  OrgFreedesktopLogin1SessionProxyPrivate *priv;
};

struct _OrgFreedesktopLogin1SessionProxyClass
{
  GDBusProxyClass parent_class;
};

GType org_freedesktop_login1_session_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrgFreedesktopLogin1SessionProxy, g_object_unref)
#endif

void org_freedesktop_login1_session_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
OrgFreedesktopLogin1Session *org_freedesktop_login1_session_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
OrgFreedesktopLogin1Session *org_freedesktop_login1_session_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void org_freedesktop_login1_session_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
OrgFreedesktopLogin1Session *org_freedesktop_login1_session_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
OrgFreedesktopLogin1Session *org_freedesktop_login1_session_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define TYPE_ORG_FREEDESKTOP_LOGIN1_SESSION_SKELETON (org_freedesktop_login1_session_skeleton_get_type ())
#define ORG_FREEDESKTOP_LOGIN1_SESSION_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_FREEDESKTOP_LOGIN1_SESSION_SKELETON, OrgFreedesktopLogin1SessionSkeleton))
#define ORG_FREEDESKTOP_LOGIN1_SESSION_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_ORG_FREEDESKTOP_LOGIN1_SESSION_SKELETON, OrgFreedesktopLogin1SessionSkeletonClass))
#define ORG_FREEDESKTOP_LOGIN1_SESSION_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_ORG_FREEDESKTOP_LOGIN1_SESSION_SKELETON, OrgFreedesktopLogin1SessionSkeletonClass))
#define IS_ORG_FREEDESKTOP_LOGIN1_SESSION_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_FREEDESKTOP_LOGIN1_SESSION_SKELETON))
#define IS_ORG_FREEDESKTOP_LOGIN1_SESSION_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_ORG_FREEDESKTOP_LOGIN1_SESSION_SKELETON))

typedef struct _OrgFreedesktopLogin1SessionSkeleton OrgFreedesktopLogin1SessionSkeleton;
typedef struct _OrgFreedesktopLogin1SessionSkeletonClass OrgFreedesktopLogin1SessionSkeletonClass;
typedef struct _OrgFreedesktopLogin1SessionSkeletonPrivate OrgFreedesktopLogin1SessionSkeletonPrivate;

struct _OrgFreedesktopLogin1SessionSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  OrgFreedesktopLogin1SessionSkeletonPrivate *priv;
};

struct _OrgFreedesktopLogin1SessionSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType org_freedesktop_login1_session_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrgFreedesktopLogin1SessionSkeleton, g_object_unref)
#endif

OrgFreedesktopLogin1Session *org_freedesktop_login1_session_skeleton_new (void);


/* ---- */

#define TYPE_OBJECT (object_get_type ())
#define OBJECT(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_OBJECT, Object))
#define IS_OBJECT(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_OBJECT))
#define OBJECT_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), TYPE_OBJECT, Object))

struct _Object;
typedef struct _Object Object;
typedef struct _ObjectIface ObjectIface;

struct _ObjectIface
{
  GTypeInterface parent_iface;
};

GType object_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (Object, g_object_unref)
#endif

OrgFreedesktopDBusPeer *object_get_org_freedesktop_dbus_peer (Object *object);
OrgFreedesktopDBusIntrospectable *object_get_org_freedesktop_dbus_introspectable (Object *object);
OrgFreedesktopDBusProperties *object_get_org_freedesktop_dbus_properties (Object *object);
OrgFreedesktopLogin1Session *object_get_org_freedesktop_login1_session (Object *object);
OrgFreedesktopDBusPeer *object_peek_org_freedesktop_dbus_peer (Object *object);
OrgFreedesktopDBusIntrospectable *object_peek_org_freedesktop_dbus_introspectable (Object *object);
OrgFreedesktopDBusProperties *object_peek_org_freedesktop_dbus_properties (Object *object);
OrgFreedesktopLogin1Session *object_peek_org_freedesktop_login1_session (Object *object);

#define TYPE_OBJECT_PROXY (object_proxy_get_type ())
#define OBJECT_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_OBJECT_PROXY, ObjectProxy))
#define OBJECT_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_OBJECT_PROXY, ObjectProxyClass))
#define OBJECT_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_OBJECT_PROXY, ObjectProxyClass))
#define IS_OBJECT_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_OBJECT_PROXY))
#define IS_OBJECT_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_OBJECT_PROXY))

typedef struct _ObjectProxy ObjectProxy;
typedef struct _ObjectProxyClass ObjectProxyClass;
typedef struct _ObjectProxyPrivate ObjectProxyPrivate;

struct _ObjectProxy
{
  /*< private >*/
  GDBusObjectProxy parent_instance;
  ObjectProxyPrivate *priv;
};

struct _ObjectProxyClass
{
  GDBusObjectProxyClass parent_class;
};

GType object_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ObjectProxy, g_object_unref)
#endif

ObjectProxy *object_proxy_new (GDBusConnection *connection, const gchar *object_path);

#define TYPE_OBJECT_SKELETON (object_skeleton_get_type ())
#define OBJECT_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_OBJECT_SKELETON, ObjectSkeleton))
#define OBJECT_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_OBJECT_SKELETON, ObjectSkeletonClass))
#define OBJECT_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_OBJECT_SKELETON, ObjectSkeletonClass))
#define IS_OBJECT_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_OBJECT_SKELETON))
#define IS_OBJECT_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_OBJECT_SKELETON))

typedef struct _ObjectSkeleton ObjectSkeleton;
typedef struct _ObjectSkeletonClass ObjectSkeletonClass;
typedef struct _ObjectSkeletonPrivate ObjectSkeletonPrivate;

struct _ObjectSkeleton
{
  /*< private >*/
  GDBusObjectSkeleton parent_instance;
  ObjectSkeletonPrivate *priv;
};

struct _ObjectSkeletonClass
{
  GDBusObjectSkeletonClass parent_class;
};

GType object_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ObjectSkeleton, g_object_unref)
#endif

ObjectSkeleton *object_skeleton_new (const gchar *object_path);
void object_skeleton_set_org_freedesktop_dbus_peer (ObjectSkeleton *object, OrgFreedesktopDBusPeer *interface_);
void object_skeleton_set_org_freedesktop_dbus_introspectable (ObjectSkeleton *object, OrgFreedesktopDBusIntrospectable *interface_);
void object_skeleton_set_org_freedesktop_dbus_properties (ObjectSkeleton *object, OrgFreedesktopDBusProperties *interface_);
void object_skeleton_set_org_freedesktop_login1_session (ObjectSkeleton *object, OrgFreedesktopLogin1Session *interface_);

/* ---- */

#define TYPE_OBJECT_MANAGER_CLIENT (object_manager_client_get_type ())
#define OBJECT_MANAGER_CLIENT(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_OBJECT_MANAGER_CLIENT, ObjectManagerClient))
#define OBJECT_MANAGER_CLIENT_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_OBJECT_MANAGER_CLIENT, ObjectManagerClientClass))
#define OBJECT_MANAGER_CLIENT_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_OBJECT_MANAGER_CLIENT, ObjectManagerClientClass))
#define IS_OBJECT_MANAGER_CLIENT(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_OBJECT_MANAGER_CLIENT))
#define IS_OBJECT_MANAGER_CLIENT_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_OBJECT_MANAGER_CLIENT))

typedef struct _ObjectManagerClient ObjectManagerClient;
typedef struct _ObjectManagerClientClass ObjectManagerClientClass;
typedef struct _ObjectManagerClientPrivate ObjectManagerClientPrivate;

struct _ObjectManagerClient
{
  /*< private >*/
  GDBusObjectManagerClient parent_instance;
  ObjectManagerClientPrivate *priv;
};

struct _ObjectManagerClientClass
{
  GDBusObjectManagerClientClass parent_class;
};

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ObjectManagerClient, g_object_unref)
#endif

GType object_manager_client_get_type (void) G_GNUC_CONST;

GType object_manager_client_get_proxy_type (GDBusObjectManagerClient *manager, const gchar *object_path, const gchar *interface_name, gpointer user_data);

void object_manager_client_new (
    GDBusConnection        *connection,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GAsyncReadyCallback     callback,
    gpointer                user_data);
GDBusObjectManager *object_manager_client_new_finish (
    GAsyncResult        *res,
    GError             **error);
GDBusObjectManager *object_manager_client_new_sync (
    GDBusConnection        *connection,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GError                **error);

void object_manager_client_new_for_bus (
    GBusType                bus_type,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GAsyncReadyCallback     callback,
    gpointer                user_data);
GDBusObjectManager *object_manager_client_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
GDBusObjectManager *object_manager_client_new_for_bus_sync (
    GBusType                bus_type,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GError                **error);


G_END_DECLS
